
<?php

  function new_feedback_menu() {
    $items['feedback'] = array(
      //title of page
      'title' => 'Feedback',
      //name of function
      'page callback' => 'main_function',
      //type of page
      'type' => MENU_NORMAL_ITEM,
      //access to page
      'access callback' => TRUE, 
    ); 
    return $items;
  }

  function contact_form($form, &$form_state){
    $form['intro'] = array(
      '#markup' => t('Use this form to send message to us'),
    );

    $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name'),
      '#required' => TRUE,
    );
    $form['old'] = array(
      '#type' => 'textfield',
      '#title' => t('Age'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integers_positive'),
    );
    $form['theme'] = array(
      '#type' => 'textfield',
      '#title' => t('Theme'),
      '#required' => TRUE,
    );
    $form['message'] = array(
      '#type' => 'textarea',
      '#title' => t('Message'),
      '#required' => TRUE,
    );
    
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    return $form;
  }   

  function element_validate_integers_positive($element, &$form_state) {
  $value = $element['#value'];
  if ($value !== '' && (!is_numeric($value) || intval($value) != $value || $value <= 0 || $value >=100 )) {
    form_error($element, t('%name must be a positive integer and less than 100.', array('%name' => $element['#title'])));
  }
}

  function main_function() {
    //obtain a form
    $form = drupal_get_form('contact_form'); 
    //rendering form
    $form = drupal_render($form); 
    return $form . 'Fields with "*" is required.';
  }

  function contact_form_submit($form, &$form_state) {
    //debug($form_state['values']);
    $name = $form_state['values']['name'];
    $old = $form_state['values']['old'];
    $theme = $form_state['values']['theme'];
    $text = $form_state['values']['message'];
    $module = 'new_feedback';
    $key = 'key';
    $language = language_default();
    $params = array();       
    $from = NULL;
    $send = FALSE;
    $email ='hadrosbk@bk.ru';
    $message = drupal_mail($module, $key, $email, $language, $params, $from, $send);
    $message['subject'] = $theme;
    $message['body'] = array();
    $message['body'][] = "Name: $name";
    $message['body'][] = "Age: $old";
    $message['body'][] = "Message: $text";
    // Retrieve the responsible implementation for this message.
    $system = drupal_mail_system($module, $key);
    // Format the message body.
    $message = $system->format($message);
    // Send e-mail.
    $message['result'] = $system->mail($message);
  } 

   
