<?php

  function new_feedback_menu() {
    $items['feedback'] = array(
      //title of page
      'title' => 'Feedback',
      //name of function
      'page callback' => 'main_function',
      //type of page
      'type' => MENU_NORMAL_ITEM,
      //access to page
      'access callback' => TRUE, 
    ); 
    return $items;
  }

  function new_feedback_form($form, &$form_state){
    $form['intro'] = array(
      '#markup' => t('Use this form to send message to us'),
    );

    $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name'),
      '#required' => TRUE,
    );
    $form['mail'] = array(
      '#type' => 'textfield',
      '#title' => t('E-mail'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_mail'),
      
    );
    $form['old'] = array(
      '#type' => 'textfield',
      '#title' => t('Age'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integers_positive'),
    );
    $form['theme'] = array(
      '#type' => 'textfield',
      '#title' => t('Theme'),
      '#required' => TRUE,
    );
    $form['message'] = array(
      '#type' => 'textarea',
      '#title' => t('Message'),
      '#required' => TRUE,
    );
    
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    return $form;
  }

  function element_validate_mail($element, &$form_state) {
    $mail = $form_state['values']['mail'];
    if (!valid_email_address($mail)) {
    form_set_error('[mail]', t('The email address appears to be invalid.'));
    }
  }

  function element_validate_integers_positive($element, &$form_state) {
    $value = $element['#value'];
    if ($value !== '' && (!is_numeric($value) || intval($value) != $value || $value <= 0 || $value >=100 )) {
      form_error($element, t('%name must be a positive integer and less than 100.', array('%name' => $element['#title'])));
    }
  }

  function main_function() {
    //obtain a form
    $form = drupal_get_form('new_feedback_form'); 
    //rendering form
    $form = drupal_render($form); 
    return $form . 'Fields with "*" is required.';
  }

  function new_feedback_mail($key, &$message, $params) {
  
      $message['subject'] = check_plain($params['theme']);
      $message['body'][] = 'Name: ' . check_plain($params['name']);
      $message['body'][] = 'E-mail: ' . check_plain($params['mail']);
      $message['body'][] = 'Age: ' . check_plain($params['old']);
      $message['body'][] = 'Message: ' . check_plain($params['message']);
  }
     

  function new_feedback_form_submit($form, &$form_state) {
    new_feedback_mail_send($form_state['values']);
  }
    
  function new_feedback_mail_send($form_values) {
      
    $module = 'new_feedback';
    $key = 'contact_message';
    $to ='hadrosbk@bk.ru';
    $language = language_default();
    $params = $form_values; 
    $from = NULL;
    $send = TRUE;
    
    $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
    if ($result['result'] == TRUE) {
      drupal_set_message(t('Your message has been sent.'));
    }
    else {
     drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
    }

  }