
<?php

  function new_feedback_menu() {
    $items['feedback'] = array(
      //заголовок страницы
      'title' => 'Online-service',
      //имя функции
      'page callback' => 'main_function',
      //тип страницы
      'type' => MENU_NORMAL_ITEM,
      //доступ к странице 
      'access callback' => TRUE, 
    ); 
    return $items;
  }

  function contact_form($form, &$form_state){
    $form['intro'] = array(
      '#markup' => t('Use this form to send message to us'),
    );

    $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name'),
      '#required' => TRUE,
    );
    $form['old'] = array(
      '#type' => 'textfield',
      '#title' => t('Age'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['theme'] = array(
      '#type' => 'textfield',
      '#title' => t('Theme'),
      '#required' => TRUE,
    );
    $form['message'] = array(
      '#type' => 'textarea',
      '#title' => t('message'),
      '#required' => TRUE,
    );
    
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    return $form;
  }   

  function main_function() {
    //получаем поля формы
    $form = drupal_get_form('contact_form'); 
    //рендерим форму
    $form = drupal_render($form); 
    return $form . 'Field with "*" is required.';
  }

  function contact_form_submit($form, &$form_state) {
    //debug($form_state['values']);
    $name = $form_state['values']['name'];
    $old = $form_state['values']['old'];
    $theme = $form_state['values']['theme'];
    $text = $form_state['values']['message'];
    $module = 'new_feedback';
    $key = 'key';
    $language = language_default();
    $params = array();       
    $from = NULL;
    $send = FALSE;
    $email ='hadrosbk@bk.ru';
    $message = drupal_mail($module, $key, $email, $language, $params, $from, $send);
    $message['subject'] = $theme;
    $message['body'] = array();
    $message['body'][] = "ФИО: $name";
    $message['body'][] = "Возраст: $old";
    $message['body'][] = "Сообщение: $text";
    // Retrieve the responsible implementation for this message.
    $system = drupal_mail_system($module, $key);
    // Format the message body.
    $message = $system->format($message);
    // Send e-mail.
    $message['result'] = $system->mail($message);
  } 

   
