<?php

function statistics_menu() {
  $items['statistics'] = array(
    //title of page
    'title' => 'Statistics',
    //name of function
    'page callback' => 'statistics_table_data_page',
    //type of page
    'type' => MENU_NORMAL_ITEM,
    //access to page
    'access callback' => TRUE, 
    ); 
  return $items;
}



function statistics_table_data_page() {
  $header = array(t('ID'), t('Name'), t('Created'));
  $rows = array();
  $query = db_select('users', 'u')
    ->fields('u', array('uid', 'name', 'created'))
    ->execute();
  while ($value = $query->fetchAssoc()) {
      if ($value['uid'] != 0) {
      $rows[] = array(
      $value['uid'],
      $value['name'],
      date("d/m/Y", $value['created'])
      );
    }
  }
  return theme('table', array('header' => $header, 'rows' => $rows));
}
 